### ISSUE TITLE
Layout shift when rendering `react-glider` container on the server

### ISSUE THREAD

**Issue by kevinfarrugia** [kevinfarrugia/react-glider#130]
At the moment, before the Glider is initialised, the items in the `glider-contain` do not appear correct and are shifted as the Glider loads.

![demo](https://user-images.githubusercontent.com/8075326/172488467-733ca741-97d1-4550-88ee-b6720da6f024.gif)

The user can choose to:
- Incur [a layout shift](https://web.dev/cls/)
- Not show the content until the Glider has initialized

This is related to an issue on Glider.js. See https://github.com/NickPiscitelli/Glider.js/pull/235

**Comment by agboolaidris** [comment]
I am also facing the same issue.
@kevinfarrugia do you forget any solution to this bug?

**Comment by kevinfarrugia** [comment]
@agboolaidris I currently recommend solving this using CSS rather than changing the underlying behavior in Glider.js. There isn't a single solution that applies for all cases, but in most cases you are able to fix this using CSS.

For example, I have [updated](https://github.com/kevinfarrugia/next-react-glider/commit/ccb104c3284cd982bbdab0b8273e2bbf4358263b) a demo built using Next: https://next-react-glider.vercel.app/ to solve this issue using CSS. In this case I added the following CSS:

```css
.track:not(:global(.glider-track)) {    
  display: flex;
  flex-direction: row;
  overflow-x: hidden;
}

.slide:not(:global(.glider-slide)) {
  flex: 0 0 calc(100% - 2rem);
}
```

I have also seen a similar technique in use on production websites, for example on https://mfa.com.mt/ where the `height` attribute of the banner is fixed and the other banners are hidden using `overflow: hidden`.
