### ISSUE TITLE
Property To Hide Scrollbar

### ISSUE THREAD

**Issue by zac-ng** [kevinfarrugia/react-glider#148]
Is there a property to hide the scrollbar while still allowing scrolling? Is there a way we can style the scroll bar?

**Comment by kevinfarrugia** [comment]
Hi @zac-ng . This can be done through CSS.

For example:

```css
/* Hide scrollbar for Chrome, Safari and Opera */
.example::-webkit-scrollbar {
  display: none;
}

/* Hide scrollbar for IE, Edge and Firefox */
.example {
  -ms-overflow-style: none;  /* IE and Edge */
  scrollbar-width: none;  /* Firefox */
}
```
